name: Pull Request Approval Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Wait for approval
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.createComment({
              issue_number: context.payload.pull_request.number,
              body: 'This pull request requires approval before it can be merged. Please review the changes and add a comment with `@approve` to approve it.',
            })

      - name: Check for approval
          id:check-approval
        uses: actions/github-script@v6
        with:
          script: |
            const { data: comments } = await github.issues.listComments({
              issue_number: context.payload.pull_request.number,
            })

            const approvals = comments.filter(comment => comment.body.toLowerCase() === '@approve')
            if (approvals.length < 1) {
              throw new Error('Pull request has not been approved.')
            } 
  
      - name: Merge pull request
        uses: actions/merge-pull-request@v4
        with:
          needs: check-approval
          merge-method: squash
          commit-message: 'Merge pull request #{{ context.payload.pull_request.number }}'