name: Deploy GitHub Pages

on:
  push:
    branches: ["develop"]
    
  workflow_run:
    workflows: ["Python Generate Pages"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy To Main Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: main
          publish_dir: ./
          personal_token: ${{ secrets.GITHUB_TOKEN }}
