name: Python Generate Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate_page:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.GIT_EMAIL }}
      USER: ${{ secrets.GIT_USER}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Sao_Paulo"
          timezoneMacos: "America/Sao_Paulo"
          timezoneWindows: "America/Sao_Paulo"


      - name: Generate Pages
        id: generate-pages
        run: |
          pip install markdown
          python3 scripts/py/load_json.py
          git config --global user.email $EMAIL
          git config --global user.name $USER
          git pull
          git add .
          git commit -m "[actions] Generate HTML page"
          git push