name: Push to main

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.GIT_EMAIL }}
      USER: ${{ secrets.GIT_USER}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Checkout 
      run: |
        git config --global user.email $EMAIL
        git config --global user.name $USER
        git checkout -b main
    - name: Push changes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TOKEN_PA }}
        delete-branch: true
    - name: Merge PR
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.TOKEN_PA }}
        pull-request-number: 1